name: Delete Workflow Runs

description: 'Deletes all workflow runs from the repository'

inputs:
  token:
    description: 'GitHub token with the necessary permissions'
    required: true
    default: '${{ github.token }}'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List and delete workflow runs
      run: |
        gh run list --json databaseId -q '.[].databaseId' |
          xargs -I ID gh api \
            "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" \
            -X DELETE
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash  # Add this line to specify the shell
