name: Format and Push

on:
  push:
    branches:
      - master

jobs:
  format-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history to avoid issues with pulling

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Black
        run: pip install black

      - name: Format Code
        run: black .

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull Latest Changes
        run: git pull origin master --rebase  # Rebase to apply new changes on top of the latest remote branch

      - name: Commit and Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
