name: City Level Gas Price Scraper

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run gas scraper
      run: |
        python "City Scrape/cityscrape.py"

    - name: Ensure directory exists
      run: |
        mkdir -p "City Scrape/Data/"

    - name: Commit and push updated CSV to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check if there are changes before committing
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes detected, skipping commit."
          exit 0
        fi
        
        git add "City Scrape/Data/City_*.csv"
        git commit -m "Update gas prices data for $(date +'%Y-%m-%d')"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
