name: Scrape and Save County Gas Prices

on:
  schedule:
    # Runs once a day at 1:00 PM UTC (7:00 AM EST). You can adjust the schedule as needed.
    - cron: "0 13 * * *"
  workflow_dispatch: # This allows manual triggering from the GitHub Actions UI.

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y wget curl unzip
        sudo apt install -y google-chrome-stable
        wget https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run gas price scraper
      run: |
        python3 realcountymain.py

    - name: Commit and push the scraped data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add RealCounty/RealCounty.csv
        git commit -m "Update gas prices data"
        git push
