name: Gas Data Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Midnight UTC for historical data
    - cron: '40 9 * * *'  # 4:40 AM UTC for live data
  workflow_dispatch:  # Allow manual triggering

jobs:
  historical_scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run historical gas scraper
        run: |
          python gashistorical.py

      - name: Verify HistoricalGasData.csv exists
        run: |
          if [ ! -f "CountyPrices/HistoricalGasData.csv" ]; then
            echo "HistoricalGasData.csv file not found!"
            exit 1
          fi

      - name: List files in CountyPrices
        run: |
          echo "Listing files in CountyPrices directory:"
          ls -l CountyPrices

      - name: Commit and push HistoricalGasData.csv to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Pull the latest changes from the remote repository
          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          
          # Force add the historical gas data file to ensure it's staged
          git add -f CountyPrices/HistoricalGasData.csv
          
          # Check if there are any changes to commit
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update historical gas data"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  live_scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run live gas scraper
        run: |
          python countygas.py

      - name: Commit and push MasterGas.csv and plot to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Pull the latest changes from the remote repository
          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          
          # Add files to git staging
          git add CountyPrices/MasterGas.csv CountyPrices/GasPrices.png
          
          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update county gas prices data for $(date +'%Y-%m-%d')"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
