name: Gas Data Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Midnight UTC for historical data
    - cron: '40 9 * * *'  # 4:40 AM UTC for live data
  workflow_dispatch:  # Allow manual triggering

jobs:
  historical_scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone to Eastern Time
        run: |
          sudo timedatectl set-timezone America/New_York

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run historical gas scraper
        run: |
          python gashistorical.py

      - name: Verify HistoricalGasData.csv exists
        run: |
          if [ ! -f "CountyPrices/HistoricalGasData.csv" ]; then
            echo "HistoricalGasData.csv file not found!"
            exit 1
          fi

      - name: List files in CountyPrices
        run: |
          echo "Listing files in CountyPrices directory:"
          ls -l CountyPrices

      - name: Print current date in Eastern Time
        run: |
          echo "Current date in Eastern Time:"
          date

      - name: Commit and push HistoricalGasData.csv to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Force add the historical gas data file to ensure it's staged
          git add -f CountyPrices/HistoricalGasData.csv
   
