name: Gas Data Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Midnight UTC for historical data
    - cron: '40 9 * * *'  # 4:40 AM UTC for live data
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape_and_append:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run live gas scraper and append data
        run: |
          python countygas.py

      - name: Verify output files exist
        run: |
          for file in CountyPrices/MasterGas.csv CountyPrices/GasPrices.png CountyPrices/FullCityGas.csv; do
            if [ ! -f "$file" ]; then
              echo "$file not found!"
              exit 1
            fi
          done

      - name: Commit and push all updated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stash any unstaged changes
          git stash --include-untracked
          
          # Pull latest changes
          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          
          # Apply stashed changes
          git stash pop || echo "No stashed changes to apply."
          
          # Add updated files to staging
          git add CountyPrices/MasterGas.csv CountyPrices/GasPrices.png CountyPrices/FullCityGas.csv
          
          # Check for changes and push
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update gas data for $(date +'%Y-%m-%d')"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
