name: Gas Price Data Scraper

on:
  schedule:
    - cron: '35 13 * * *'  # This will run daily at 1:35 PM ET
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  historical-scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run historical scrape
        run: |
          python gashistorical.py

  live-scrape:
    runs-on: ubuntu-latest
    needs: historical-scrape  # Ensures live scrape waits for historical scrape

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run live scrape and combine
        run: |
          python countygas.py
          
      - name: Commit combined data and push to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CountyPrices/FullCityGas.csv
          git add CountyPrices/GasPrices.png
          git commit -m "Update combined gas data"
          git push
