name: Daily County Gas Scraper

on:
  schedule:
    - cron: '15 14 * * *'  # Runs at 10:15 AM Eastern Time (converted to UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust version if necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run county gas scraper
      run: |
        python countygas.py

    - name: Commit and push MasterGas.csv and plot to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add CountyPrices/MasterGas.csv  # Commit only the MasterGas.csv
        git add CountyPrices/GasPrices.png  # Commit the plot file
        git commit -m "Update county gas prices data for $(date +'%Y-%m-%d')"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
