name: Gas Scraper Jobs

on:
  schedule:
    - cron: '45 9 * * *'  # Scheduled to run daily at 19:45 UTC for the live scraper
    - cron: '35 18 * * *'  # Scheduled to run daily at 10:30 UTC for historical scraper
  workflow_dispatch:  # Allow manual triggering for both jobs

jobs:
  scrape-daily:
    name: Daily County Gas Scraper
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run county gas scraper
        run: |
          python countygas.py

      - name: Commit and push MasterGas.csv and plot to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CountyPrices/MasterGas.csv CountyPrices/GasPrices.png
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update county gas prices data for $(date +'%Y-%m-%d')"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  scrape-historical:
    name: Historical Gas Data Scraper
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run historical gas scraper
        run: |
          python gashistorical.py

      - name: Commit and push historical data to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CountyPrices/HistoricalGasData.csv
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update historical gas prices data for $(date +'%Y-%m-%d')"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
