name: County Prices
on:
  schedule:
    # Runs once a day at 1:00 PM UTC (7:00 AM EST). Adjust the schedule as needed.
    - cron: "0 12 * * *"
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI.

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Set timezone to Eastern Time
      run: |
        sudo timedatectl set-timezone America/New_York

    - name: Checkout repository
      uses: actions/checkout@v3  # Ensure using the most recent checkout action

    - name: Set up Python 3.9
      uses: actions/setup-python@v4  # Use Python 3.9 as per your preference
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run gas price scraper
      run: |
        python3 RealCounty/county_scraper_main.py
        
    - name: Commit and push the scraped data
      run: |
        # Ensure Git user configuration is correct
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Check if there are any changes (to avoid errors if nothing changed)
        git diff --exit-code || echo "Changes detected"

        # Add new or modified files in the 'Data' directory
        git add ./Data/* || echo "No new files to add"

        # Commit the changes
        git commit -m "Update gas prices data" || echo "No changes to commit"

        # Push the changes to the repository
        git push
