name: Delete Workflow Runs Example

on:
  push:
    branches:
      - main

jobs:
  delete_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        uses: ./.github/actions/deleteworkflows
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
